from typing import TypedDict, List, Annotated, Sequence
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    """
    Represents the state of our LangGraph Agentic RAG system.
    """
    # The history of chat messages, annotated so that new messages are appended
    messages: Annotated[list, add_messages]
    
    # The current user query or reformulated search query
    query: str
    
    # The list of retrieved document chunks (from local DB or web search)
    documents: List[object]
    
    # The final answer text generated by the LLM
    generation: str
    
    # A list of reasoning steps recorded during execution (e.g. ["retrieve", "generate"])
    steps: List[str]
